### ISSUE TITLE
Add more strict message about M1 + system Ruby installation

### ISSUE THREAD

**Issue by terrakok** [Kotlin/kdoctor#16]
There is a problem with system Ruby on M1 macs when someone tries to use cocoapod-generate gem. It looks like error:
```log
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle (LoadError)
```
or something like this.

Work around is to use custom Ruby installation (and reinstall cocoapods and cocoapod-generate gems): https://youtrack.jetbrains.com/issue/KT-49418#focus=Comments-27-5429773.0-0

It would be better to help `kdoctor` users with this case

**Comment by vkormushkin** [comment]
doctor already shows an info message if system ruby installation is used:

```
 * System ruby is currently used
          Consider installing ruby via Homebrew, rvm or other package manager in case of issues with cocoapods installation
```

Do you think the output should be more detailed for M1 users? My concern is that there are few ways to install ruby and providing instructions on how to install and set up system PATH for all of them may be verbose.

**Comment by terrakok** [comment]
Yes. For M1 we should show strict error because system Ruby on M1 is broken and Cocoapods gem doesn't work
