### ISSUE TITLE
Cocoapods failure not appropriate when Cocoapods support is not desired

### ISSUE THREAD

**Issue by derekleerock** [Kotlin/kdoctor#21]
Hello friends!

First of all - thank you for building this tool for KMM development! I was excited when I saw it mentioned in the Kotlin blog a little while back as I've been using KMM for the last couple of years. 

I just ran the tool and here is the output that was generated for reference:

```
[v] System
    OS: macOS (12.4)
    CPU: Apple M1 Max
[v] Java
    Java (openjdk version "11.0.12" 2021-07-20)
    Location: /Library/Java/JavaVirtualMachines/Android Studio JRE/Contents/Home/bin/java

    JAVA_HOME=/Library/Java/JavaVirtualMachines/Android Studio JRE/Contents/Home

    * Note that, by default, Android Studio uses bundled JDK for Gradle tasks execution.
          Gradle JDK can be configured in Android Studio Preferences under Build, Execution, Deployment -> Build Tools -> Gradle section

[v] Android Studio
    Android Studio (2021.2)
    Location: /Applications/Android Studio.app
    Bundled Java: openjdk 11.0.12 2021-07-20
    Kotlin Plugin: 212-1.7.0-release-281-AS5457.46
    Kotlin Multiplatform Mobile Plugin: 0.3.3(212-1.7.0-RC-release-217-IJ)-104

[v] Xcode
    Xcode (13.4.1)
    Location: /Applications/Xcode.app

[x] Cocoapods
    * ruby version ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin21] is not compatible with cocoapods-generate
      More details: https://github.com/rubygems/rubygems/issues/4338
          Downgrade ruby to version < 3.0.0

    ruby (ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin21])

    ruby gems (3.2.3)

    cocoapods (1.11.2)

    * cocoapods-generate plugin not found
          Get cocoapods-generate from https://github.com/square/cocoapods-generate#installation

Failures: 1
KDoctor has diagnosed one or more problems while checking your environment.
Please check the output for problem description and possible solutions.
```

While I happen to have Cocoapods installed (via Homebrew) for some other Xcode projects, based on personal preference for my own projects, I do not use Cocoapods. Therefore, receiving information regarding how cocoapods is not configured properly for me is irrelevant. 

I'm not sure if there are other developers who are similar to me, however, if there are, then I would suggest it might be helpful to make the Cocoapods confirmation optional as it is not required for KMM (or iOS) development, or change the verification result from "error" to warning with a stipulation that it is only important if you are actively using Cocoapods.

**Comment by sebj** [comment]
Agreed! We recently migrated over from Cocoapods to Swift Package Manager + a shared framework in our KMM project, so the failing Cocoapods check is irrelevant to us.

**Comment by terrakok** [comment]
At the moment, the Cocoapods plugin is the only convenient way to add external native dependencies into your project. So, kdoctor forces to install it. We don't want to make kdoctor another one tool with lots of options and modes to run. We try to keep it simple and easy to use.

**Comment by derekleerock** [comment]
@terrakok Thanks for your response. I appreciate you must be very busy. However, not receiving any acknowledgment or response more than 9 months after this issue was opened does not give me much confidence that the KDoctor tool is being reliably developed and maintained. 

> We don't want to make kdoctor another one tool with lots of options and modes to run. We try to keep it simple and easy to use.

It appears that my request may have been misinterpreted, as my proposal was not to add options or modes for running KDoctor. 

My proposal was to change the confirmation for the status of the user's Cocoapod installation from a required one to an optional one. 

Currently, the check is a requirement and causes an error. This communicates to the end-user that their configuration is wrong or invalid. Cocoapod integration is **not** required for any KMM projects, and I have never used Cocoapods on any of my KMM projects. 

My proposal is to change the output the tool generates for this check from a requirement to an optional configuration option which instead outputs a warning. This could state whether that Cocoapods integration is configured properly or not, and that it is not a requirement for configuring your KMM environment (which it is not). 

I think this maintains the tool's simplicity without adding additional options or modes to run. 

Maybe an example would help. Instead of the current failure, it could look something like this:

```
*** REQUIRED FOR KMM DEVELOPMENT ***

[v] System
    OS: macOS (12.4)
    CPU: Apple M1 Max

[v] Java
    Java (openjdk version "11.0.12" 2021-07-20)
    Location: /Library/Java/JavaVirtualMachines/Android Studio JRE/Contents/Home/bin/java

    JAVA_HOME=/Library/Java/JavaVirtualMachines/Android Studio JRE/Contents/Home

    * Note that, by default, Android Studio uses bundled JDK for Gradle tasks execution.
          Gradle JDK can be configured in Android Studio Preferences under Build, Execution, Deployment -> Build Tools -> Gradle section

[v] Android Studio
    Android Studio (2021.2)
    Location: /Applications/Android Studio.app
    Bundled Java: openjdk 11.0.12 2021-07-20
    Kotlin Plugin: 212-1.7.0-release-281-AS5457.46
    Kotlin Multiplatform Mobile Plugin: 0.3.3(212-1.7.0-RC-release-217-IJ)-104

[v] Xcode
    Xcode (13.4.1)
    Location: /Applications/Xcode.app

Failures: 0


*** OPTIONAL FOR KMM DEVELOPMENT ***

[ ] Cocoapods
    * ruby version ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin21] is not compatible with cocoapods-generate
      More details: https://github.com/rubygems/rubygems/issues/4338
          Downgrade ruby to version < 3.0.0

    ruby (ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin21])

    ruby gems (3.2.3)

    cocoapods (1.11.2)

    * cocoapods-generate plugin not found
          Get cocoapods-generate from https://github.com/square/cocoapods-generate#installation

Warnings: 1
```

Please let me know what else I can clarify if you have any questions about my request. It's also worth noting that several other users have expressed an interest in this request. Thanks for your kind consideration.

**Comment by terrakok** [comment]
I have to mention that installed cocoapods don't break cocoapods-less projects but provide support for all others. For example, all Compose multiplatform projects require cocoapods.

**Comment by derekleerock** [comment]
> I have to mention that installed cocoapods don't break cocoapods-less projects but provide support for all others. For example, all Compose multiplatform projects require cocoapods.

I'm not entirely sure I understand how this is related to this issue; if anything, this supports my proposal in that not all Kotlin Multiplatform projects do not require Compose. (I do not use Compose in any of my production KMM apps.) Therefore, this is in line with my proposal that Cocoapods is also not a requirement. 

> So, the answer is: kdoctor is a tool for an onboarding and first environment setup. The Cocoapods plugin is part of the required environment for lots of projects. We don't want to overload a kdoctor output optional cases and hints which requires to research what is nedeed and what is not. If you are an experienced user, it is OK to skip some requirements.

I'm really disappointed to hear this. If the purpose of kdoctor is to give users the confidence that their environment is set up properly for development, then communicating to them that Cocoapods is a required component that carries the same weight and importance as the others, is misleading and potentially confusing, regardless of their experience level.

**Comment by terrakok** [comment]
Following your logic, Android Studio should be an optional environment component because you can develop without it :)
Cocoapods is a required component that carries the same weight and importance as the other. It's true.

**Comment by sebj** [comment]
> Following your logic, Android Studio should be an optional environment component because you can develop without it

This is a false equivalence.

> Cocoapods is a required component

It isn't. If it was "required" our build would be failing, or we would be experiencing issues during development. Neither are true.

We've happily used Kotlin Multiplatform dependencies in our shared module (and Swift Package Manager dependencies in our iOS platform project) for over a year. We did not at any point feel that anything was missing from this setup.

Refusal to acknowledge that Cocoapods isn't necessary or required just increases the difficulty for teams, especially iOS teams, trying to migrate to KMM in an existing project. It seems hard enough to get the iOS community to engage with and try KMM as is, let alone when the tooling is inflexible and produces an incorrect and irrelevant error. Many existing iOS codebases integrating KMM use Swift Package Manager, and a number of new and junior devs won't even have knowledge of Cocoapods.

If you're unwilling to to provide any options or flags, downgrading Cocoapods from an error to a warning would at least be a step in the right direction.
