### ISSUE TITLE
Confirmation of Gradle project configuration worth considering? 

### ISSUE THREAD

**Issue by derekleerock** [Kotlin/kdoctor#22]
Hello friends!

First of all - thank you for building this tool for KMM development! I was excited when I saw it mentioned in the Kotlin blog a little while back, as I've been using KMM for the last couple of years. 😃

I am curious about how you envision this tool evolving in the future. 

The most challenging aspect of KMM development that I have found is managing and maintaining the Gradle configuration for the shared modules using Gradle. As KMM has evolved and the Gradle configuration needs to change, it has been challenging for me to determine the proper Gradle configuration for all components to work together harmoniously. Once it's working, I tend to try not to touch it as I perceive it to be quite brittle, and even still sometimes IntelliJ will indicate issues with the configuration even though it appears to be working to me. My "Gradle-fu" is admittedly relatively limited, and I desire to focus on the development of the product and not get lost in configuration details, so these are likely contributing factors. 

Specifically, I'm referring to the `build.gradle.kts` (or `build.gradle`) file for any shared module. This includes the configuration of the targets (Android, iOS, or otherwise), Android-specific configuration, and the configuration for building the framework to be used with iOS (including Debug/Release/Custom build configurations, managing architectural differences such as simulator vs. device, etc.). 

If this is a part of your vision for this product, then I'd be willing to get involved in some conversations about how I might be able to contribute to this somehow. If this isn't a part of your vision - no worries at all, and maybe I can look to find a better place to share this feedback. I just thought it might be worth asking here to see. 👍🏻

Thanks for your kind consideration! 🙇🏻‍♂️

**Comment by terrakok** [comment]
Hello! Thank you for your feedback.
Latest kdoctor has a special key to check user projects as well.
Try to run `kdoctor -a` inside the project folder.

**Comment by erokhins** [comment]
This question seems to be at least partially answered. Issues on GitHub for KDoctor project are disabled, please use the [KDoctor](https://youtrack.jetbrains.com/issues/KT?q=Subsystems:%20KDoctor%20) subsystem in Kotlin issue tracker if you have future questions.
